//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeForHomeless.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HFH_dbEntities : DbContext
    {
        public HFH_dbEntities()
            : base("name=HFH_dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<freeService> freeServices { get; set; }
        public virtual DbSet<VictoriaCharity> VictoriaCharities { get; set; }
        public virtual DbSet<VolunteerCenter> VolunteerCenters { get; set; }
    }
}
